import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { AuthProvider } from "@/components/providers/AuthProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShadCN Tutorial",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  const isAuthenticated = !!cookieStore.get("accessToken")?.value;
  const pathname = cookieStore.get("next-url")?.value || "/";
  
  // Check if this is an auth page (login, register, etc.)
  const isAuthPage = pathname.startsWith('/auth/');

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            {isAuthPage ? (
              // Auth pages don't have sidebar/navbar
              <>{children}</>
            ) : (
              // Home page and authenticated pages have sidebar/navbar
              <div className="flex">
                <SidebarProvider defaultOpen={defaultOpen}>
                  <AppSidebar />
                  <main className="w-full">
                    <Navbar />
                    <div className="px-4">{children}</div>
                  </main>
                </SidebarProvider>
              </div>
            )}
            <Toaster position="top-right" />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}